-- CreateEnum
CREATE TYPE "VehicleStatus" AS ENUM ('AVAILABLE', 'BOOKED', 'MAINTENANCE', 'BLOCKED');

-- AlterTable
ALTER TABLE "Vehicle" ADD COLUMN "status" "VehicleStatus" NOT NULL DEFAULT 'AVAILABLE';
ALTER TABLE "Vehicle" ADD COLUMN "seatingCapacity" INTEGER NOT NULL DEFAULT 4;

-- AlterTable
ALTER TABLE "Booking" ADD COLUMN "pickupCity" TEXT;
ALTER TABLE "Booking" ADD COLUMN "dropCity" TEXT;
ALTER TABLE "Booking" ADD COLUMN "pickupLat" DOUBLE PRECISION;
ALTER TABLE "Booking" ADD COLUMN "pickupLng" DOUBLE PRECISION;
ALTER TABLE "Booking" ADD COLUMN "dropLat" DOUBLE PRECISION;
ALTER TABLE "Booking" ADD COLUMN "dropLng" DOUBLE PRECISION;
ALTER TABLE "Booking" ADD COLUMN "bufferMinutes" INTEGER;
