ALTER TYPE "BookingAuditAction" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "BookingAuditAction" ADD VALUE IF NOT EXISTS 'DISPATCHER_REJECTED';
ALTER TYPE "BookingAuditAction" ADD VALUE IF NOT EXISTS 'DISPATCHER_CANCELLED';
