-- Booking review flags for admin dispute handling
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "isUnderReview" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "adminReviewNote" TEXT;

-- Admin booking intervention audit actions
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'FORCE_CANCEL_BOOKING';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'REASSIGN_BOOKING';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'EXTEND_DISPATCHER_DEADLINE';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'SET_BOOKING_REVIEW';

-- Booking timeline admin actions
ALTER TYPE "BookingAuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_FORCE_CANCELLED';
ALTER TYPE "BookingAuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_REASSIGNED';
ALTER TYPE "BookingAuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_EXTENDED_DEADLINE';
ALTER TYPE "BookingAuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_MARKED_REVIEW';
ALTER TYPE "BookingAuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_UNMARKED_REVIEW';
